-- Migration: 054_team_deletion_pending — adds the 'deletion_pending'
-- intermediate status to the team-deletion state machine so a partial
-- worker-side destruction failure leaves a recoverable, reconciler-visible
-- marker instead of a half-deleted team.
--
-- WHY THIS EXISTS
-- ---------------
-- Migration 032 gave teams.status three values: active, deletion_requested,
-- tombstoned. The worker's team_deletion_executor sweep destroys customer
-- DBs, k8s namespaces, and S3 backups, then flips the row to 'tombstoned'.
-- If a step in that destruction pipeline fails mid-way, the row stayed in
-- 'deletion_requested' — indistinguishable from a team still inside its
-- 30-day grace window. An operator could not tell "grace clock running" from
-- "destruction started and crashed", and the API restore endpoint would
-- happily resurrect a team whose customer DBs were already dropped.
--
-- 'deletion_pending' closes that gap. The executor flips
-- deletion_requested -> deletion_pending the moment it BEGINS destruction
-- (grace window has elapsed, teardown is now in flight). From that point:
--   - the restore endpoint refuses (destruction has started, not safe to
--     resurrect),
--   - a mid-pipeline failure leaves the row in deletion_pending (NOT
--     half-tombstoned),
--   - the worker orphan-sweep reconciler treats deletion_pending +
--     tombstoned as the two "owning team is gone" states and finishes /
--     retries the teardown.
--
-- The lifecycle is now:
--   active -> deletion_requested -> deletion_pending -> tombstoned
--                    |                     |
--                    v                     v
--                 (restore)         (reconciler retries on failure)
--
-- WHY THE CHECK IS DROPPED + RE-ADDED
-- -----------------------------------
-- Postgres has no "ALTER CONSTRAINT ... ADD VALUE" for a CHECK. The
-- constraint name was system-generated by migration 032's inline CHECK
-- (teams_status_check). We drop it IF EXISTS and re-add a named one so this
-- migration is idempotent on re-run and the constraint name is now explicit
-- for any future migration.

ALTER TABLE teams
    DROP CONSTRAINT IF EXISTS teams_status_check;

ALTER TABLE teams
    ADD CONSTRAINT teams_status_check
    CHECK (status IN ('active','deletion_requested','deletion_pending','tombstoned'));

-- Extend the partial index so the worker's candidate scans (which now also
-- look at deletion_pending rows for the orphan-sweep retry path) stay index-
-- backed. A separate partial index keeps each index small and the query
-- planner honest — the executor scans deletion_requested, the reconciler
-- scans deletion_pending.
CREATE INDEX IF NOT EXISTS idx_teams_deletion_pending
    ON teams(deletion_requested_at) WHERE status = 'deletion_pending';
